# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='documents',
            name='key',
        ),
        migrations.AddField(
            model_name='keyword',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Documents'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='key',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='authors',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Documents'),
        ),
    ]
