# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20180330_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='author',
        ),
    ]
