# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_documents_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='folder_label',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
