# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20180412_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='folder',
            name='label',
            field=models.CharField(max_length=20),
        ),
    ]
