# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-10 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20180412_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='abstract',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(upload_to='document', validators=[user.models.Documents.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='folder_label',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
